version: "3.3"
services:
  backend:
    container_name: backend
    image: painelsaudefiocruz/painel-esus
    build:
      context: painelsaude/
      dockerfile: Dockerfile
    environment:
      - HOST=
      - DATABASE=
      - USER=
      - PASSWORD=
      - PORT=5432
      - CIDADE=SUSÓPOLIS
      - ESTADO=FC
      - ADMIN_USR=
      - ADMIN_PASS=
      - POPULATION=20000
    ports:
      - "5001:5001"
