version: "3.3"
services:
  backend:
    container_name: backend
    image: painelsaudefiocruz/painel-esus
    build:
      context: painelsaude/
      dockerfile: Dockerfile
    environment:
      - HOST=paineisirece.ckebriuhritw.sa-east-1.rds.amazonaws.com
      - DATABASE=esus
      - USER=susopolis_user
      - PASSWORD=R6Hi1J4HMkInYmvQ6iMdId8J2Lz7PP
      - PORT=5432
      - CIDADE=SUSÓPOLIS
      - ESTADO=FC
      - ADMIN_USR=admin
      - ADMIN_PASS=admin
      - POPULATION=20000
    ports:
      - "5001:5001"
