# @name login
POST http://localhost:5001/v1/auth
Content-Type: application/json

{"username": "admin", "password": "FCadmin23"}

###

@token = {{login.response.body.$.data}}



GET http://localhost:5001/v1/demographic/age-groups
Authorization: Bearer {{token}}
###
GET http://localhost:5001/v1/demographic/gender
Authorization: Bearer {{token}}

###
GET http://localhost:5001/v1/demographic/ibge-population
Authorization: Bearer {{token}}
###
GET http://localhost:5001/v1/demographic/location-area
Authorization: Bearer {{token}}
###
GET http://localhost:5001/v1/demographic/location-area/diabetes
Authorization: Bearer {{token}}
###
GET http://localhost:5001/v1/demographic/location-area/hypertension
Authorization: Bearer {{token}}
###
GET http://localhost:5001/v1/demographic/location-area/child
Authorization: Bearer {{token}}
###
GET http://localhost:5001/v1/demographic/location-area/elderly
Authorization: Bearer {{token}}
###
GET http://localhost:5001/v1/demographic/total-people
Authorization: Bearer {{token}}