repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
            "--rcfile=painel-esus/.pylintrc", # Link to your config file
            "--load-plugins=pylint.extensions.docparams", # Load an extension
          ]
  - repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c 'painel-esus/venv/bin/pip3 freeze > painel-esus/requirements.txt; git add painel-esus/requirements.txt'
        language: system
        pass_filenames: false
        stages: [commit]