POST http://localhost:5001/v1/auth
Content-Type: application/json

{"username": "admin", "password": "FCadmin23"}

###

GET http://localhost:5001/v1/elderly/total-ubs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiY25zIjoiMDAwMDAwMDAwMCIsInVmIjoiIiwibXVuaWNpcGlvIjoiIiwicHJvZmlsZXMiOlsiYWRtaW4iXSwiZXF1aXBlIjpudWxsLCJ1YnMiOm51bGwsImV4cCI6MTc0NDM0NDI0N30.7sLqWlr3v85Nb1jDtphKdlfhyl9wBNk_s8vNpFUu8nQ

###

GET http://localhost:5001/v1/elderly/total-medical-cares
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiY25zIjoiMDAwMDAwMDAwMCIsInVmIjoiIiwibXVuaWNpcGlvIjoiIiwicHJvZmlsZXMiOlsiYWRtaW4iXSwiZXF1aXBlIjpudWxsLCJ1YnMiOm51bGwsImV4cCI6MTc0NDM0NDI0N30.7sLqWlr3v85Nb1jDtphKdlfhyl9wBNk_s8vNpFUu8nQ

###
GET http://localhost:5001/v1/elderly/total-ubs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiY25zIjoiMDAwMDAwMDAwMCIsInVmIjoiIiwibXVuaWNpcGlvIjoiIiwicHJvZmlsZXMiOlsiYWRtaW4iXSwiZXF1aXBlIjpudWxsLCJ1YnMiOm51bGwsImV4cCI6MTc0NDM0NDI0N30.7sLqWlr3v85Nb1jDtphKdlfhyl9wBNk_s8vNpFUu8nQ

###
GET http://localhost:5001/v1/elderly/total-medical-cares
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiY25zIjoiMDAwMDAwMDAwMCIsInVmIjoiIiwibXVuaWNpcGlvIjoiIiwicHJvZmlsZXMiOlsiYWRtaW4iXSwiZXF1aXBlIjpudWxsLCJ1YnMiOm51bGwsImV4cCI6MTc0NDM0NDI0N30.7sLqWlr3v85Nb1jDtphKdlfhyl9wBNk_s8vNpFUu8nQ

###
GET http://localhost:5001/v1/elderly/by-gender
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiY25zIjoiMDAwMDAwMDAwMCIsInVmIjoiIiwibXVuaWNpcGlvIjoiIiwicHJvZmlsZXMiOlsiYWRtaW4iXSwiZXF1aXBlIjpudWxsLCJ1YnMiOm51bGwsImV4cCI6MTc0NDM0NDI0N30.7sLqWlr3v85Nb1jDtphKdlfhyl9wBNk_s8vNpFUu8nQ

###
GET http://localhost:5001/v1/elderly/by-race
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiY25zIjoiMDAwMDAwMDAwMCIsInVmIjoiIiwibXVuaWNpcGlvIjoiIiwicHJvZmlsZXMiOlsiYWRtaW4iXSwiZXF1aXBlIjpudWxsLCJ1YnMiOm51bGwsImV4cCI6MTc0NDM0NDI0N30.7sLqWlr3v85Nb1jDtphKdlfhyl9wBNk_s8vNpFUu8nQ

###
GET http://localhost:5001/v1/elderly/two-height-records
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiY25zIjoiMDAwMDAwMDAwMCIsInVmIjoiIiwibXVuaWNpcGlvIjoiIiwicHJvZmlsZXMiOlsiYWRtaW4iXSwiZXF1aXBlIjpudWxsLCJ1YnMiOm51bGwsImV4cCI6MTc0NDM0NDI0N30.7sLqWlr3v85Nb1jDtphKdlfhyl9wBNk_s8vNpFUu8nQ

###
GET http://localhost:5001/v1/elderly/two-acs-visits
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiY25zIjoiMDAwMDAwMDAwMCIsInVmIjoiIiwibXVuaWNpcGlvIjoiIiwicHJvZmlsZXMiOlsiYWRtaW4iXSwiZXF1aXBlIjpudWxsLCJ1YnMiOm51bGwsImV4cCI6MTc0NDM0NDI0N30.7sLqWlr3v85Nb1jDtphKdlfhyl9wBNk_s8vNpFUu8nQ

###
GET http://localhost:5001/v1/elderly/creatinine
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiY25zIjoiMDAwMDAwMDAwMCIsInVmIjoiIiwibXVuaWNpcGlvIjoiIiwicHJvZmlsZXMiOlsiYWRtaW4iXSwiZXF1aXBlIjpudWxsLCJ1YnMiOm51bGwsImV4cCI6MTc0NDM0NDI0N30.7sLqWlr3v85Nb1jDtphKdlfhyl9wBNk_s8vNpFUu8nQ

###
GET http://localhost:5001/v1/elderly/influenza-vaccines
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiY25zIjoiMDAwMDAwMDAwMCIsInVmIjoiIiwibXVuaWNpcGlvIjoiIiwicHJvZmlsZXMiOlsiYWRtaW4iXSwiZXF1aXBlIjpudWxsLCJ1YnMiOm51bGwsImV4cCI6MTc0NDM0NDI0N30.7sLqWlr3v85Nb1jDtphKdlfhyl9wBNk_s8vNpFUu8nQ

###
GET http://localhost:5001/v1/elderly/dentist-appointment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiY25zIjoiMDAwMDAwMDAwMCIsInVmIjoiIiwibXVuaWNpcGlvIjoiIiwicHJvZmlsZXMiOlsiYWRtaW4iXSwiZXF1aXBlIjpudWxsLCJ1YnMiOm51bGwsImV4cCI6MTc0NDM0NDI0N30.7sLqWlr3v85Nb1jDtphKdlfhyl9wBNk_s8vNpFUu8nQ

###
GET http://localhost:5001/v1/elderly/ivcf-20
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiY25zIjoiMDAwMDAwMDAwMCIsInVmIjoiIiwibXVuaWNpcGlvIjoiIiwicHJvZmlsZXMiOlsiYWRtaW4iXSwiZXF1aXBlIjpudWxsLCJ1YnMiOm51bGwsImV4cCI6MTc0NDM0NDI0N30.7sLqWlr3v85Nb1jDtphKdlfhyl9wBNk_s8vNpFUu8nQ

###