# pylint: disable=W0611
from .oral_health_get_all_cares_by_place import OralHealthGetAllCaresByPlaceController
from .oral_health_get_cares_by_age_range import OralHealthGetCaresByAgeRangeController
from .oral_health_get_cares_by_gender import OralHealthGetCaresByGenderController
from .oral_health_get_cares_by_line_of_services_controller import \
    OralHealthGetCaresByLineOfServicesController
from .oral_health_get_cares_by_outcome import OralHealthGetCaresByOutcomeController
from .oral_health_get_cares_by_place import OralHealthGetCaresByPlaceController
from .oral_health_get_cares_by_type_of_services_controller import \
    OralHealthGetCaresByTypeOfServicesController
from .oral_health_get_total_controller import OralHealthGetTotalController
from .oral_health_get_total_extraction_proportion import OralHealthGetExtractionProceduresProportionController
