from .group_by_sexo import filter_by_sexo
from .indicador_diabetes import get_indicators_diabetes
from .indicador_hipertensao import get_indicators_hipertensao
from .sexo_faixa_etaria import filter_by_gender_age
from .tipo_localidade import filter_by_localidade
