from .create_dim_equipes_base_repository import CreateDimEquipesBaseRepository
from .create_dim_racacor_repository import CreateDimRacaCorBaseRepository
from .create_fat_atend_indiv_odonto_repository import CreateAtendOdontoBaseRepository
from .create_fat_atend_indiv_repository import CreateAtendIndivBaseRepository
from .create_fat_cad_domiciliar_repository import CreateCadDomiciliarBaseRepository
from .create_fat_cad_individual_repository import CreateCadIndividualBaseRepository
from .create_fat_cidacao_pec_repository import CreateCidacaoPecBaseRepository
from .create_fat_familia_terr_repository import CreateFamiliaTerrBaseRepository
from .create_fat_proced_atend_repository import CreateProcedAtendBaseRepository
from .create_fat_vacinacao_repository import CreateVacinacaoBaseRepository
from .create_fat_visita_domic_repository import CreateVisistaDomiciliarBaseRepository
from .create_indicadores_criancas_repository import CreateIndicadoresCriancasRepository
from .create_indicadores_equipe_repository import CreateIndicadoresEquipeRepository
from .create_indicadores_idosos_repository import CreateIndicadoresIdososRepository
from .create_tb_acomp_cidadaos_vinculados_repository import (
    CreateAcompCidadaosVinculadosBaseRepository,
)
from .create_tb_cidacao_repository import CreateCidadaoBaseRepository
from .create_tb_cidciap_explode_atendimentos_repository import (
    CreateCidCiapExplodeAtendimentosRepository,
)
from .create_tb_dim_cbo_base_repository import CreateTbDimCboRepository
from .create_tb_equipe_repository import CreateEquipeBaseRepository
from .create_tb_tipo_equipe_repository import CreateTipoEquipeBaseRepository
from .create_unidade_saude_base_repository import CreateUnidadesSaudeBaseRepository
