name: Build and Deploy to Private Docker Hub

on:
  push:
    branches: [v1.0.15.3.1]
jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        run: |
          # curl -X POST -H 'Content-type: application/json' --data '{"text":"Deploy painel-esus gerado com sucesso! Versão: ${{ env.RELEASE_VERSION }}"}' ${{ secrets.SLACK_WEBHOOK_URL }}
          echo "${{ github.head_ref || github.ref_name }}"
