name: Build and Deploy to Private Docker Hub

on:
  push:
    branches: [v1.0.15.3.1]
jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        run: |
          curl -X POST ${{ secrets.SLACK_WEBHOOK_URL }} \
            -H 'Content-type: application/json' \
            --data-binary @- << EOF
            {
                "text": "*Instalador Gerado* :caixa_de_entrada:\n
            O processo de construção do instalador foi finalizado.\n
            Versão: *${{ github.head_ref || github.ref_name }}*"    
            }
            EOF 
