name: Build and Deploy to Private Docker Hub

on:
  push:
    branches: [v*]

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10" # Use the Python version you need

      - name: Install PyInstaller
        working-directory: ./painel-esus
        run: |
          ls -la
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Build EXE config
        working-directory: ./painel-esus
        run: |
          pyinstaller --icon=.\icon\config.ico -n config --onefile interface.py
          cd dist
          ls -la

      - name: Build EXE run
        working-directory: ./painel-esus
        run: |
          pyinstaller --icon=.\icon\Icon_Painel_Purple_ICO.ico -n painel-esus --onefile run.py
          cd dist
          ls -la   

      - name: Upload config artifact
        uses: actions/upload-artifact@v3
        with:
          name: config
          path: ./painel-esus/dist/config

      - name: Upload run artifact
        uses: actions/upload-artifact@v3
        with:
          name: run
          path: ./painel-esus/dist/painel-esus

      - name: Create backend environment
        working-directory: ./painel-esus
        run: |
          cat <<EOF > .env
          ${{ vars.ENV_BACK }}
          EOF

      - name: Extract version from branch name
        id: extract_version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/heads/release/}" >> $GITHUB_ENV


  build-linux-artfact:
    needs:  [build-backend]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: Download files config
        uses: actions/download-artifact@v3
        with:
          name: config
          path: ./dist/config
      - run: ls

      - name: Download files painel
        uses: actions/download-artifact@v3
        with:
          name: run
          path: ./dist/painel-esus
      - run: ls

      - name: Create empty files
        run: |
          # Cria arquivos vazios
          touch painel_esus.db painel-esus.sqls


      - name: Validate files and compress
        run: |
          tar -czf compressed_file.tar.gz \
            -C /home/runner/work/painel-esus/painel-esus/painel-esus ibge.csv \
            -C /home/runner/work/painel-esus/painel-esus/painel-esus icon \
            -C /home/runner/work/painel-esus/painel-esus/paineis-v2-front static-files \
            -C /home/runner/work/painel-esus/painel-esus painel_esus.db \
            -C /home/runner/work/painel-esus/painel-esus painel-esus.sqls \
            -C /home/runner/work/painel-esus/painel-esus config \
            -C /home/runner/work/painel-esus/painel-esus painel-esus \

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: compressed-file
          path: compressed_file.tar.gz
