name: Build and Deploy to Private Docker Hub

on:
  push:
    branches: [release/*]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # - name: Build Docker image
      #   run: docker build -t docker build . -t painelsaudefiocruz/demo:backend-1.0.0 .

      # - name: Push Docker image to Docker Hub
      # run: docker push docker build . -t painelsaudefiocruz/demo:backend-1.0.0
