name: Build and Deploy to Private Docker Hub

on:
  push:
    branches: [v1*]

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: ./paineis-v2-front
        run: yarn

      - name: Build React project
        working-directory: ./paineis-v2-front
        run: |
          cat <<EOF > .env
          ${{ vars.ENV_FRONT }}
          EOF
          CI=false npm run build --prod
         
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10" # Use the Python version you need

      - name: Install PyInstaller
        working-directory: ./painel-esus
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Create backend environment
        working-directory: ./painel-esus
        run: |
          cat <<EOF > .env
          ${{ vars.ENV_BACK }}
          EOF

      - name: Extract version from branch name
        id: extract_version
        run: |
          echo "RELEASE_VERSION=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" 
          echo "RELEASE_VERSION=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
  notify-slack:
    runs-on: ubuntu-latest
    needs: build-backend

    steps:
      - name: Notify Slack
        run: |
          echo  ${{ env.RELEASE_VERSION }}
          #curl -X POST -H 'Content-type: application/json' --data '{"text":"Deploy painel-esus gerado com sucesso! Versão: ${{ env.RELEASE_VERSION }}"}' ${{ secrets.SLACK_WEBHOOK_URL }}
 
