name: Build and Deploy to Private Docker Hub

on:
  push:
    branches: [release/*]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: ./paineis-v2-front
        run: yarn

      - name: Build React project
        working-directory: ./paineis-v2-front
        run: |
          cat <<EOF > .env
          ${{ vars.ENV_FRONT }}
          EOF
          ls -la
          CI=false npm run build --prod

      - name: Create backend environment
        working-directory: ./painel-esus
        run: |
          cat <<EOF > .env
          ${{ vars.ENV_BACK }}
          EOF
          ls -la

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_USERNAME }} | docker login -u ${{ secrets.DOCKER_ACCESS_TOKEN }} --password-stdin

      - name: Build Docker image
        run: docker build -t docker build . -t painelsaudefiocruz/demo:backend-1.0.0 .

      - name: Push Docker image to Docker Hub
        run: docker push docker build . -t painelsaudefiocruz/demo:backend-1.0.0
